# src/api/v1/schemas/query_schema.py

from pydantic import BaseModel, Field
from typing import List, Optional


# =========================
# Request Schema
# =========================
class QueryRequest(BaseModel):
    query: str = Field(
        ...,
        example="What is gross revenue in FY24?",
        description="User's natural language query"
    )


# =========================
# Retrieved Chunk Schema
# =========================
class RetrievedResult(BaseModel):
    """
    Represents a single retrieved document chunk with all fields flattened.
    """
    chunk_id: int = Field(description="Unique identifier for the chunk")

    content: str = Field(description="Text content of the chunk")

    # Metadata fields
    chunk_type: Optional[str] = Field(
        default=None,
        description="Type of chunk (text, table, image, etc.)"
    )
    page: Optional[int] = Field(
        default=None,
        description="Page number in the source document"
    )
    section: Optional[str] = Field(
        default=None,
        description="Section name of the chunk"
    )
    source: Optional[str] = Field(
        default=None,
        description="Source document file name"
    )
    image_path: Optional[str] = Field(
        default=None,
        description="Path to image if chunk contains image"
    )

    similarity: Optional[float] = Field(
        default=None,
        description="Similarity score from retrieval"
    )

    created_date: Optional[str] = Field(
        default=None,
        description="Document creation date"
    )
    updated_date: Optional[str] = Field(
        default=None,
        description="Document last updated date"
    )


# =========================
# Response Schema
# =========================
class QueryResponse(BaseModel):
    """
    Final API response returned to the user.
    Supports both:
    - RAG (retrieved_results populated)
    - NL2SQL (sql fields populated)
    """

    query: str = Field(
        description="Original query submitted by the user"
    )

    answer: str = Field(
        description="Final answer generated by the system"
    )

    # RAG Output
    retrieved_results: List[RetrievedResult] = Field(
        default_factory=list,
        description="Top reranked document chunks used to generate the answer"
    )

    # NL2SQL Output
    sql_query: Optional[str] = Field(
        default=None,
        description="SQL query generated and executed (only for NL2SQL flow)"
    )

    sql_result: Optional[str] = Field(
        default=None,
        description="Raw SQL execution result (only for NL2SQL flow)"
    )